modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="hexgodofstories"
version="0.5.2-warping"
displayName="HexGodOfStories"
authors="21M4rco"
description='''Illusion, sorcery, conjuration and command of time. Powers are granted by an operator with /hgos, never by default.'''
[[dependencies.hexgodofstories]]
modId="forge"
mandatory=true
versionRange="[47.4.10,)"
ordering="NONE"
side="BOTH"
[[dependencies.hexgodofstories]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
[[dependencies.hexgodofstories]]
modId="playeranimator"
mandatory=true
versionRange="[1.0.0,)"
ordering="AFTER"
side="CLIENT"
